Fix flake8 errors
terhorstd/nest-simulator pull request #14
Opened 2022-03-07 16:22 UTC by pnbabu

- Add error and warning codes to flake8 `--ignore` list
- Fix the errors raised by flake8 on `.py` files in `pynest` directory

2022-03-07 16:45 UTC, terhorstd commented on pynest/nest/lib/hl_api_helper.py
> +uni_str = str
do we need both?

2022-03-08 06:21 UTC, jougs commented on .github/workflows/nestbuildmatrix.yml
> +          flake8 pynest/
Shouldn't we also run this on the tests in `testsuite`?

2022-03-08 06:21 UTC, jougs commented on pynest/nest/__init__.py
> +        _rel_import_star(self, ".lib.hl_api_types")                 # noqa: F821
:heart:

2022-03-08 06:21 UTC, jougs commented on pynest/nest/__init__.py
> +# `F821 undefined name` where these variables are used. Hence we mark all these
```suggestion
# `F821 undefined name` where these variables are used. Hence we mark all those
```

2022-03-08 09:05 UTC, pnbabu commented on .github/workflows/nestbuildmatrix.yml
> +          flake8 pynest/
Yes, there are also some `.py` files outside of `pynest` and `testsuite` directories. So I think it is better to run flake8 on the entire nest repository.

2022-03-08 13:51 UTC, jougs requested changes
Just two more minor removals and we're good to merge from my side

2022-03-08 13:51 UTC, jougs commented on pynest/nest/lib/hl_api_spatial.py
>          # 3D layer
```suggestion
```

2022-03-08 13:51 UTC, jougs commented on pynest/nest/lib/hl_api_spatial.py
>          # 3D layer
```suggestion
```

2022-03-08 14:03 UTC, pnbabu commented
> Just two more minor removals and we're good to merge from my side

After running flake8 on the entire repository, there are more errors to be fixed. I think we should merge this after fixing them.

2022-03-08 15:39 UTC, terhorstd commented on pynest/nest/__init__.py
> +        _rel_import_star(self, ".lib.hl_api_types")                 # noqa: F821
:rocket:

2022-03-11 17:06 UTC, terhorstd approved these changes
Thanks @pnbabu ! That is already a lot of fixing you added here! :rocket: 

LGTM

2022-03-11 17:06 UTC, merged